Repository GrantChain/GrantFox, pull requests merged in 2025-05, with the labels that each got.

#18 [FEAT]: Add role management
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/api/(auth)/check-role/[user_id]/route.ts
  src/app/api/(auth)/forgot-password/route.ts
  src/app/api/(auth)/register-role/route.ts
  src/app/dashboard/layout.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/footer/FooterLanding.tsx
  src/components/modules/auth/hooks/use-role-check.ts
  src/components/modules/auth/schema/role-selection.schema.ts
  src/components/modules/auth/services/register-role.service.ts
  src/components/modules/auth/ui/forms/ForgotPassword.tsx
  src/components/modules/auth/ui/forms/LoginForm.tsx
  src/components/modules/auth/ui/forms/ResetPasswordForm.tsx
  src/components/modules/auth/ui/pages/ResetPasswordClient.tsx
  src/components/modules/auth/ui/role-selection-modal.tsx
  src/components/modules/auth/ui/role-selection-provider.tsx
  src/components/ui/dialog.tsx
  src/hooks/password-reset.hook.ts
Labels: enhancement, May be rewarded, Maintainer - Joel Vargas, External Dev

#21 Feat/available grants display
  package.json
  src/app/dashboard/opportunities/page.tsx
  src/components/layout/sidebar/app-sidebar.tsx
  src/components/modules/grants/hooks/use-grants.hook.ts
  src/components/modules/grants/services/grants.service.ts
  src/components/modules/grants/ui/grants-section.tsx
  src/components/modules/grants/ui/grants-table.tsx
  src/components/ui/select.tsx
  src/components/ui/table.tsx
Labels: enhancement, non-rewarded, ODHack13, Maintainer - Joel Vargas, External Dev

#23 [FEAT]: Add resend email and fixed google sign in
  package-lock.json
  package.json
  src/components/modules/auth/hooks/auth.hook.ts
  src/components/modules/auth/store/auth.store.ts
  src/components/modules/auth/ui/forms/LoginForm.tsx
  src/components/modules/auth/ui/forms/SignUpForm.tsx
  src/components/modules/auth/ui/google/GoogleSignInButton.tsx
  src/components/modules/auth/ui/pages/Verify.tsx
Labels: enhancement, ODHack13, Maintainer - Joel Vargas, External Dev

#22 Feat/sidebar
  src/components/layout/sidebar/app-sidebar.tsx
  src/components/layout/sidebar/nav-user.tsx
Labels: enhancement, ODHack13, Maintainer - Joel Vargas, External Dev

#28 Feat/create biome husky rules
  .husky/commit-msg
  .husky/pre-commit
  README.md
  biome.json
  commitlint.config.js
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: enhancement, ODHack13, Maintainer - Joel Vargas, External Dev
