Repository GrantChain/GrantFox, pull requests merged in 2025-06, with the labels that each got.

#47 Refact/tw and db and types
  prisma/schema.prisma
  src/@types/application.entity.ts
  src/@types/date.entity.ts
  src/@types/enums.ts
  src/@types/escrow/escrow-endpoint.entity.ts
  src/@types/escrow/escrow-payload.entity.ts
  src/@types/escrow/escrow-response.entity.ts
  src/@types/escrow/escrow.entity.ts
  src/@types/grant-provider.entity.ts
  src/@types/grant.entity.ts
  src/@types/grantee.entity.ts
  src/@types/http.entity.ts
  src/@types/milestone-submission.entity.ts
  src/@types/milestone.entity.ts
  src/@types/pagination.entity.ts
  src/@types/project.entity.ts
  src/@types/system-log.entity.ts
  src/@types/team.entity.ts
  src/@types/user.entity.ts
  src/app/api/(auth)/check-role/[user_id]/route.ts
  src/app/api/(auth)/register-role/route.ts
  src/app/api/(auth)/register-user/route.ts
  src/app/layout.tsx
  src/components/modules/auth/context/UserContext.tsx
  src/components/modules/auth/services/check-role.service.ts
  src/components/modules/auth/services/register-role.service.ts
  src/components/modules/grants/ui/components/GrantCard.tsx
  src/components/providers/global.provider.tsx
  src/components/providers/posthog.provider.tsx
  src/lib/axios.ts
  src/lib/trustless-work.ts
Labels: enhancement, Core Dev, ODHack 14

#40 feat: added github third party auth
  .env.example
  middleware.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  src/components/modules/auth/hooks/useAuth.ts
  src/components/modules/auth/ui/forms/LoginForm.tsx
  src/components/modules/auth/ui/forms/SignUpForm.tsx
  src/components/modules/auth/ui/github/GithubSignInButton.tsx
  src/lib/prisma.ts
Labels: enhancement, External Dev, ODHack 14, Maintainer - Marco Araya

#50 Feat/create reusable kanban board
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/dev/page.tsx
  src/components/ui/kanban/DraggableCard.tsx
  src/components/ui/kanban/KanbanColumn.tsx
  src/hooks/useKanbanParams.ts
  src/interfaces/kanban.interface.ts
Labels: enhancement, Maintainer - Joel Vargas, Core Dev, External Dev, ODHack 14
